### PR TITLE
FLOW-2238 Add input to increment version number 

### PR DESCRIPTION
**Pull request by andreas-leanix**
Add an input parameter that allows to increment the version number even if the commit already has been tagged.
Split the CI into two jobs to avoid problems on job reruns with other parts of the tests.

### CODE REVIEW

**Review by dan-leanix — APPROVED** [review]
@andreas-leanix LGTM.

@perbernhardt Would be great if you could have a look too. Thanks!

**Comment by andreas-leanix** [comment]
Situation: We use two repos, one for the workflow service and one for the third party repos (workflow-diagram).
When working normally, we don't want to include the workflow-diagram in our daily work, so it is excluded from tests of the workflow service. But when it comes to deployments, we need to add the workflows in that repo to the deployment.
Problem: When we release a third party workflow only, we merge to master on that repo and trigger a deployment on the latest master version of workflow that then includes the newest changes from workflow-diagram. This deployment doesn't work because there is nothing changed in the workflow repo.
We want to increase the version number in case the workflow-diagram repo triggers a deployment.

**Comment by perbernhardt** [comment]
> Situation: We use two repos, one for the workflow service and one for the third party repos (workflow-diagram).
> When working normally, we don't want to include the workflow-diagram in our daily work, so it is excluded from tests of the workflow service - workflow-diagram has its own pipeline. But when it comes to deployments, we need to add the workflows in that repo to the deployment.
> Problem: When we release a third party workflow only, we merge to master on that repo and trigger a deployment on the latest master version of workflow that then includes the newest changes from workflow-diagram. This deployment doesn't work because there is nothing changed in the workflow repo.
> We want to increase the version number in case the workflow-diagram repo triggers a deployment.

Well.. And here we are with a quite complicated setup that nobody will really understand in some month. I also wonder how you actually control what ends up in production and when? So do you run a manual workflow then to deploy your main repository without that it changed? I even wonder if this is actually allowed in terms of ISO policy...

So I would have an idea how to make that more transparent & perhaps robust: You could use git-submodules to actually reflect that your main repository uses some specific version of the other repository. This would have two advantages:
1. You don't get what ever is just there in the other repository, but instead precisely reference a revision of it within your main repository.
2. A update of the submodule will need a commit on the main repository, hence explicitly reflecting the change and also already creating a new version tag with the action that we have.

**Comment by perbernhardt** [comment]
And of course there would also be the simple option to merge both repositories again. Github actions allows to filter for changes in certain directories. With this you could run the "expensive tests" only if something in the third-party folder changes. In all other cases, simply only run the main test suites. Problem solved?

**Comment by andreas-leanix** [comment]
The setup is quite simple, since the repo only contains bpmn files that are linked into the workflow service when it runs a master deployment.
Every PR is reviewed by us on each repo, so no problem with ISO here.
When we set up this the way it is now, the deployment worked. The release action did a change during the last year that related in this not working any more.
submodules have other disadvantages and we decided against it at the time.
I will consider our options.

**Comment by andreas-leanix** [comment]
Taking monorepo approach for workflow repos.

**Pull request closed without merging**
