### PR TITLE
SENSE-5344 add ssh param

### PR DESCRIPTION
**Pull request by philipp-leanix**
Add ssh param to docker build, e.g to enable checkout of a private github repository.

Test deployment worked: https://github.com/leanix/sense/runs/4444481662?check_suite_focus=true

### CODE REVIEW

**Comment by dan-leanix** [comment]
@philipp-leanix Without this adjustment and only the `webfactory/ssh-agent@v0.4.1` action in your workflow file your build does not work, correct?

**Comment by perbernhardt** [comment]
> @philipp-leanix Without this adjustment and only the `webfactory/ssh-agent@v0.4.1` action in your workflow file your build does not work, correct?

This would also be my question :-)

**Review by perbernhardt — COMMENTED** [review]
Why not using webfactory/ssh-agent@v0.4.1?

**Comment by philipp-leanix** [comment]
We're using the ssh agent action. AFAICT this only sets up the ssh key for the github runner, but we also need to forward the ssh key to the docker build action. https://github.com/webfactory/ssh-agent#using-the-dockerbuild-push-action-action even mentions how to use it with the official docker build-push action.

**Comment by dan-leanix** [comment]
@philipp-leanix Have you tried it without the modifications?

The reason why I am asking is that we use the https://github.com/leanix/infrastructure-as-code-action in our IaC repos which is pre-build Docker container and in some IaC repos we pull Terraform module from another repo within our LeanIX org without explicitly specifying the SSH sock.

**Comment by philipp-leanix** [comment]
If I use the current action the run [fails](https://github.com/leanix/sense/runs/4445791859?check_suite_focus=true) ( matching [commit](https://github.com/leanix/sense/commit/4c93bdecb7ce7da21c2314517398c240c4c7f593)).


Also looks like we need buildx if we want to pass ssh ( [run](https://github.com/leanix/sense/runs/4445630929?check_suite_focus=true), [commit](https://github.com/leanix/sense/commit/fd2c003b8f865b6ab4adf87a2c44b8a3f91171e8)). If enable-cache is false, build instead of buildx is used, which does not know `--ssh`.

**Review by perbernhardt — APPROVED** [review]
Understood. I was wondering whether we just use the SSH_AUTH_SOCK by default, but I am also fine with just adding this parameter...

**Review by dan-leanix — APPROVED** [review]

**Comment by philipp-leanix** [comment]
@perbernhardt @dan-leanix I also switched to use buildkit even if enable-cache is set to false. Are you fine with that? 

According to this [search](https://github.com/search?q=org%3Aleanix+enable-cache%3A+false&type=code) everyones using buildx anyway.

**Review by perbernhardt — APPROVED** [review]

**Pull request merged**
